/**
 * Checklist-style site survey report (no letter grades / scores).
 */

import fs from "node:fs/promises";
import path from "node:path";
import { reportPath, FOREMAN_DIR } from "./lib/paths.js";
import { detectStack, pickTemplateId } from "./detect.js";
import { auditCursorSetup, stackFindings, topFixes } from "./audit.js";
import { loadPreferences } from "./preferences.js";

const STATUS_ICON = {
  ok: "✅",
  warn: "⚠️",
  missing: "❌",
};

/**
 * @param {import("./audit.js").Finding} finding
 */
export function formatFindingLine(finding) {
  const icon = STATUS_ICON[finding.status] || "•";
  return `${icon} ${finding.area} — ${finding.message}`;
}

/**
 * @param {object} opts
 * @param {string} opts.repoName
 * @param {import("./preferences.js").ForemanPreferences | null} opts.prefs
 * @param {import("./detect.js").StackDetection} opts.stack
 * @param {import("./audit.js").Finding[]} opts.findings
 * @param {string} opts.templateId
 * @param {string} [opts.generatedAt]
 */
export function renderReportMarkdown(opts) {
  const {
    repoName,
    prefs,
    stack,
    findings,
    templateId,
    generatedAt = new Date().toISOString(),
  } = opts;

  const vibe = prefs?.vibe || "fun";
  const boring = vibe === "boring";
  const title = boring
    ? `# Site Survey — ${repoName}`
    : `# 🚧 Site Survey — ${repoName}`;

  const prefLine = prefs
    ? boring
      ? `Preferences: ${prefs.vcs} · ${prefs.issues} · pm=${prefs.packageManager || stack.preferredPackageManager || "unset"} · copy=${prefs.vibe}`
      : `> Vibe: ${prefs.vibe} · Preferences: **${prefs.vcs}** + **${prefs.issues}** + **${prefs.packageManager || stack.preferredPackageManager || "unset"}**`
    : boring
      ? "Preferences: not set — run the questionnaire on first /scan"
      : "> Preferences: not set yet — hard-hat check will run on first `/scan`";

  const stackSection = findings.filter((f) =>
    ["Stack", "Languages", "Frameworks", "Package manager", "package.json", "Security surface"].includes(
      f.area,
    ),
  );
  const cursorSection = findings.filter(
    (f) => !stackSection.includes(f),
  );

  const fixes = topFixes(findings, 3);
  const fixesBlock =
    fixes.length === 0
      ? boring
        ? "No high-impact gaps detected. Optional polish still welcome via /build."
        : "Looking solid 🏗️ — no critical gaps. You can still run `/build` for polish."
      : fixes
          .map((f, i) => `${i + 1}. ${f.message}${f.fixId ? ` (\`${f.fixId}\`)` : ""}`)
          .join("\n");

  const cta = boring
    ? "Run `/build` to apply the selected fixes (non-destructive; backup + confirm first)."
    : "👉 Run `/build` to fix these (non-destructive; backup + confirm first).";

  const redo = boring
    ? "Redo questionnaire: re-run `/scan` and choose redo prefs."
    : "Redo questionnaire: re-run `/scan` and say **redo** when asked.";

  return `${title}
> Generated by Robo Foreman \`/scan\` · ${generatedAt}
${prefLine}

## Preferences
${
  prefs
    ? `- VCS: ${prefs.vcs} · Issues: ${prefs.issues} · PM: ${prefs.packageManager || stack.preferredPackageManager || "unset"} · Copy: ${prefs.vibe}
- ${redo}`
    : `- ${redo}`
}

## Stack
${stackSection.map(formatFindingLine).join("\n") || "- (no stack findings)"}

**Template hint:** \`${templateId}\`  
**Scripts seen:** ${stack.scripts.length ? stack.scripts.join(", ") : "(none)"}

## Cursor agent setup
${cursorSection.map(formatFindingLine).join("\n") || "- (no setup findings)"}

## Highest-impact fixes (top 3)
${fixesBlock}

${cta}
`;
}

/**
 * Run full survey and optionally write `.foreman/report.md`.
 * @param {string} repoRoot
 * @param {{ write?: boolean, repoName?: string }} [opts]
 */
export async function generateReport(repoRoot, opts = {}) {
  const prefs = await loadPreferences(repoRoot);
  const stack = await detectStack(repoRoot);
  const { findings: cursorFindings, meta } = await auditCursorSetup(repoRoot);
  const findings = [
    ...stackFindings(stack, { packageManager: prefs?.packageManager }),
    ...cursorFindings,
  ];
  const templateId = pickTemplateId(stack);
  const repoName =
    opts.repoName ||
    path.basename(path.resolve(repoRoot)) ||
    "project";

  const markdown = renderReportMarkdown({
    repoName,
    prefs,
    stack,
    findings,
    templateId,
  });

  const result = {
    markdown,
    findings,
    stack,
    prefs,
    templateId,
    meta,
    topFixes: topFixes(findings, 3),
    reportFile: reportPath(repoRoot),
  };

  if (opts.write !== false) {
    await fs.mkdir(path.join(repoRoot, FOREMAN_DIR), { recursive: true });
    await fs.writeFile(result.reportFile, markdown, "utf8");
  }

  return result;
}
